name: Deploy

on:
 # push:
   # branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout modular-server
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Checkout blog-posts
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caiocampos/blog-posts
        path: out/blog-posts
    - name: Copy blog-posts files
      run: |
           mkdir -p ./src/modules/blog-posts
           cp -r ./out/blog-posts/back/src/* ./src/modules/blog-posts
           rm -rf ./out/blog-posts
           ls ./src/modules/blog-posts
    - name: Checkout asteroid-score
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caiocampos/asteroid-score
        path: out/asteroid-score
    - name: Copy asteroid-score files
      run: |
           mkdir -p ./src/modules/asteroid-score
           cp -r ./out/asteroid-score/src/* ./src/modules/asteroid-score
           rm -rf ./out/asteroid-score
           ls ./src/modules/asteroid-score
    - name: Checkout shrtr
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caiocampos/shrtr
        path: out/shrtr
    - name: Copy shrtr files
      run: |
           mkdir -p ./src/modules/shrtr
           cp -r ./out/shrtr/shrtr/src/* ./src/modules/shrtr
           rm -rf ./out/shrtr
           ls ./src/modules/shrtr
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install
    - name: Build
      run: npm run build:full --if-present
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dist
        folder: dist
